name: "Refresh jdk25 from Upstream"
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
env:
  UPSTREAM_REMOTE: https://github.com/openjdk/jdk25u
  LOCAL_BRANCH: develop
  
jobs:
    refresh-jdk:
        runs-on: ubuntu-latest
        name: "Update Corretto-25"
        if: github.repository_owner == 'corretto'
        steps:
            - name: "Checkout code"
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
                ref: ${{ env.LOCAL_BRANCH }}
                
            - name: "Configure the user"
              run: |
                git config user.email "no-reply@amazon.com"
                git config user.name "corretto-github-robot"
                
            - name: "Merge openjdk/jdk25u:master to the corretto-25:develop"
              run: |
                git fetch $UPSTREAM_REMOTE master || exit 1
                git merge -m "Merge upstream-jdk" FETCH_HEAD
                
            - name: "Update Corretto version"
              shell: bash
              run: bash ./.github/scripts/update-version.sh $UPSTREAM_REMOTE

            - name: "Push to the corretto-25"
              run: git push origin $LOCAL_BRANCH

            # Different merges to branches
            - name: "Merge Corretto-25 develop to nightly"
              shell: bash
              run: |
                git checkout nightly
                git restore --source origin/$LOCAL_BRANCH --staged --worktree -- version.txt
                git commit --allow-empty -m "Ephemeral commit: Automerged version.txt from $LOCAL_BRANCH to nightly"
                ephemeral_commit=$(git rev-parse HEAD)
                git merge origin/$LOCAL_BRANCH
                git rebase --onto ${ephemeral_commit}^ ${ephemeral_commit}
                git push origin nightly